apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense # create a namespace for expense project
  labels:
    component: mysql
    project: expense
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
  #pod definition
  template:
    metadata:
      labels:
        component: mysql
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: sharanya0510/mysql:v1.0

